---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: sysstat-opensuse-leap
    image: opensuse:leap
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        sysstat_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: opensuse-leap
verifier:
  name: goss
  lint:
    name: yamllint
