---
# tasks file for sysstat
- name: install sysstat
  package:
    name: "{{ sysstat_packages }}"
    state: present
  register: sysstat_install_sysstat
  until: sysstat_install_sysstat is succeeded
  retries: 3

- name: start and enable sysstat
  service:
    name: "{{ sysstat_service }}"
    state: started
    enabled: yes
  when:
    - sysstat_service | length
