---
# tasks file for sysstat
- name: install sysstat
  package:
    name: "{{ sysstat_packages }}"
    state: present

- name: start and enable sysstat
  service:
    name: "{{ sysstat_service }}"
    state: started
    enabled: yes
  when:
    - sysstat_service | length
